# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-17 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_name', models.CharField(default=0, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(default=0, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('mboto', models.ImageField(blank=True, upload_to='upload_storage/')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pictures.Section')),
                ('location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pictures.pin')),
            ],
        ),
    ]
