# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-17 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pictures.Section'),
        ),
        migrations.AddField(
            model_name='upload',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pictures.pin'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_name',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
    ]
